ITEM_MAPPING = { -- apID = tracker item code
-- badges
[1] = {"CoalBadge", "toggle"},
[2] = {"ForestBadge", "toggle"},
[3] = {"CobbleBadge", "toggle"},
[4] = {"FenBadge", "toggle"},
[5] = {"RelicBadge", "toggle"},
[6] = {"MineBadge", "toggle"},
[7] = {"IcicleBadge", "toggle"},
[8] = {"BeaconBadge", "toggle"},
-- key items
[9] = {"Bicycle", "toggle"},
[10] = {"Super Rod"},
[11] = {"Journal"},
[12] = {"Vs. Seeker"},

[19] = {"Lucky Egg", "toggle"},

[76] = {"Flash", "toggle"},
[77] = {"Cut", "toggle"},
[78] = {"Fly", "toggle"},
[79] = {"Surf", "toggle"},
[80] = {"Strength", "toggle"},
[81] = {"RockSmash", "toggle"},
[82] = {"Waterfall", "toggle"},
[83] = {"RockClimb", "toggle"},

[84] = {"Pokétch", "toggle"},

[85] = {"Memo Pad App", "toggle"},
[86] = {"Pedometer App", "toggle"},
[87] = {"Pokémon List App", "toggle"},
[88] = {"Friendship Checker App", "toggle"},
[89] = {"Dowsing Machine App", "toggle"},
[90] = {"Pokémon History App", "toggle"},
[91] = {"Counter App", "toggle"},
[92] = {"Coin Toss App"},
[93] = {"Dot Artist App"},
[94] = {"Roulette App"},
[95] = {"Color Changer App"},
[96] = {"Alarm Clock App"},

[111] = {"[EVENT] Regirock Defeated"},
[112] = {"Master's Mark"},
[113] = {"Magma Stone"},
[114] = {"Hall Pass"},
[115] = {"Gold Token"},
[116] = {"Rental Coupon 1"},
[117] = {"Rental Coupon 2"},
[118] = {"Rental Coupon 3"},
[119] = {"Castle Point Card"},
[120] = {"1 Castle Point"},
[121] = {"Machine Part"},
[122] = {"Battle Castle Silver Print"},
[123] = {"Battle Arcade Silver Print"},
[124] = {"Battle Hall Silver Print"},
[125] = {"Battle Factory Silver Print"},
[126] = {"10 BP"},
[127] = {"Point Card"},
[128] = {"Silver Token"}
}